<?php if($added): ?>
	<?php include(dirname(__FILE__).'/modal-window.php'); ?>
<?php endif; ?>
<table id="ct2" class="catalog-list">	<thead>		<tr id="ct_sort">			<th width="45">Арт.</th>			<th>Название</th>
			<?php if($this->Authmodel->settings('show_char') == 1): ?>
			<th width="50">Характеристика</th>
			<?php endif; ?>			<th width="70">Цена</th>			<th class="qty" width="30">Кол-во</th>			<th class="total" width="90">Сумма</th>			<th class="remove-row"></th>		</tr>	</thead>	<tbody>		<?php if($this->Cart_model->list_categories()): ?>			<?php foreach($this->Cart_model->list_categories() as $one): ?>					<tr class="head" id="<?php echo $one->guid;?>">					<td style="color: #04A3F5; font-weight: bold; text-align: left;" colspan="<?php if($this->Authmodel->settings('show_char') == 1) echo '3'; else echo '2'; ?>"><span>+</span> <?php echo $this->Cart_model->list_cat($one->guid); ?></td>					<td><?php echo number_format($this->Cart_model->cat_price_one($one->guid),2); ?></td>					<td class="qty"><?php echo $this->Cart_model->cat_num($one->guid); ?></td>					<td class="total"><?php echo number_format($this->Cart_model->cat_price($one->guid),0); ?></td>					<td class="remove-row"></td>				</tr>				<?php $i = 0; ?> 				<?php foreach($this->Cart_model->list_orders($one->guid) as $two): ?>					<?php $i++; ?>					<?php $evro = $two->evro; ?> 					<tr id="line<?php echo $two->orderid;?>" <?php if($i%2 == 0) echo 'class="block '.$one->guid.' even"';?> class="block <?php echo $one->guid;?>" style="display: none;">						<td style="font-size: 12px;" width="45"><?php echo $two->articule;?></td>						<td><?php echo $two->name;?></td>
						<?php if($this->Authmodel->settings('show_char') == 1): ?>
						<td width="50" id="char_<?php echo $two->orderid;?>"><?php echo $this->Cart_model->get_char($two->char_guid); ?></td>
						<?php endif; ?>						<td width="60"><?php $price=number_format($two->price*$evro,0); echo $price;?></td>						<td class="qty" width="30"><input onkeypress="change_cart_enter(this,'<?php echo $two->orderid;?>',event);" class="input_num" type="text" name="" value="<?php echo $two->number;?>" /></td>						<td class="total" width="90"><span id="l_p<?php echo $two->orderid;?>"><?php echo number_format($two->price_rur,0); ?></span></td>                                						<td class="remove-row"><a class="remove-row" order_id="<?php echo $two->orderid;?>" href="#" title="Удалить строку"><img alt="" src="/img/btn-close.png" /></a></td>					</tr>				<?php endforeach; ?>			<?php endforeach; ?>		<?php endif; ?>		 	</tbody></table><div class="table_summ">	Общее количество: <span id="all_pos"><?php echo number_format($cat['allgoods'],0);?></span> | Сумма заказа: <span id="all_price"><?php echo number_format($cat['allsumm'],0);?> руб.</span> </div><?php if($i>0): ?>	<div class="table_comment">		<textarea onchange="comment();" onblur="if(!value)value=defaultValue" onfocus="if(value==defaultValue)value=''" class="comment_text" style="margin: 10px 0;" name="comment_text" cols="30" rows="3">Добавьте комментарий к заказу...</TEXTAREA><br>	</div><?php endif; ?>